dir = File.dirname(__FILE__)
require File.join(dir, *%w[compiler lexical_address_space])
require File.join(dir, *%w[compiler ruby_builder])
require File.join(dir, *%w[compiler node_classes])
require File.join(dir, *%w[compiler metagrammar])
require File.join(dir, *%w[compiler grammar_compiler])
require File.join(dir, *%w[compiler load_grammar])
