dir = File.dirname(__FILE__)

require 'rubygems'
require 'rake'
require 'spec/rake/spectask'
Gem::manage_gems
require 'rake/gempackagetask'
require 'rake/testtask'

task :default => :test

Rake::TestTask.new do |t|
  t.pattern = 'test/**/*test.rb'
end

gemspec = Gem::Specification.new do |s|
  s.name = "Treetop"
  s.version = "0.1.0"
  s.author = "Nathan Sobo"
  s.email = "nathansobo@gmail.com"
  s.homepage = "http://functionalform.blogspot.com"
  s.platform = Gem::Platform::RUBY
  s.summary = "A Ruby-based text parsing and interpretation DSL"
  s.files = FileList["{test,lib}/**/*"].to_a
  s.require_path = "lib"
  s.autorequire = "treetop"
  s.has_rdoc = false
end

Rake::GemPackageTask.new(gemspec) do |pkg|
  pkg.need_tar = true
end

namespace :metagrammar do
  task :generate do |object|
    require "#{dir}/lib/treetop"
    Treetop::MetagrammarBootstrapper.generate_metagrammar
  end
end