require File.join(File.dirname(__FILE__), '..', 'spec_helper')
require 'benchmark'

module CircularCompilationSpec
  describe "a compiler generated by the compiler under test" do
    attr_reader :input
    
    before do
      File.open(METAGRAMMAR_PATH, 'r') do |file|
        @input = file.read
      end
      result = Trusted::Treetop::Compiler::MetagrammarParser.new.parse(input)
      compiled_metagrammar_parser_source = result.compile
      
      # Replace stale metagrammar parser with newly compiled version
      Treetop::Compiler.send(:remove_const, :Metagrammar)
      Treetop::Compiler.send(:remove_const, :MetagrammarParser)
      Object.class_eval(compiled_metagrammar_parser_source)
    end

    it "can parse the metagrammar.treetop whence it came" do
      result = Treetop::Compiler::MetagrammarParser.new.parse(input)
      result.should be_success
    end
  end
end
