require File.join(File.dirname(__FILE__), *%w[.. spec_helper])

describe "A terminal symbol" do
  before do
    @terminal = TerminalSymbol.new("foo")
  end
    
  it "returns the correct interval for a prefix starting after 0" do
    result = @terminal.parse_at("xfoo", 1, parser_with_empty_cache_mock)
    result.interval.should == (1...4)
    
    result = @terminal.parse_at("---foo", 3, parser_with_empty_cache_mock)
    result.interval.should == (3...6)
  end
  
  it "shouldn't parse nonmatching input at the index even if a match occurs later in the input" do
    @terminal.parse_at(" foo", 0, parser_with_empty_cache_mock).should be_failure
  end
  
  it "has a string representation" do
    @terminal.to_s.should == '"foo"'
  end
end

describe "The result of TerminalSymbol#parse_at for a matching input prefix at a given index" do
  before do
    @terminal = TerminalSymbol.new("foo")
    @parser = parser_with_empty_cache_mock
    input = ("foobar")
    @result = @terminal.parse_at(input, 0, @parser)
  end
  
  it "is an instance of SuccessfulParseResult" do
    @result.should be_success
  end
  
  it "is successful" do
    @result.should be_success
  end
  
  it "has a text value matching the terminal symbol" do
    @result.text_value.should == @terminal.prefix
  end
  
  it "is a kind of TerminalSyntaxNode" do
    @result.should be_a_kind_of(TerminalSyntaxNode)
  end
end

describe "The result of TerminalSymbol#parse_at for a non-matching input prefix at a given index" do
  before do
    @terminal = TerminalSymbol.new("foo")
    @parser = parser_with_empty_cache_mock
    input = ("barfoo")
    @start_index = 0
    @result = @terminal.parse_at(input, @start_index, @parser)
  end
  
  it "is an instance of of TerminalParseFailure" do
    @result.should be_an_instance_of(TerminalParseFailure)
  end
  
  it "has a consumed interval that start and end at the start index of the parse" do
    @result.interval.should == (@start_index...@start_index)    
  end
  
  it "retains reference to the failing terminal symbol" do
    @result.expression.should == @terminal
  end
  
  it "has itself as a nested failure" do
    @result.nested_failures.should == [@result]
  end
end

describe "A terminal symbol with a method defined in its node class" do
  before do
    @terminal = TerminalSymbol.new("foo")
    @terminal.node_class_eval do
      def method
      end
    end
  end
  
  it "returns nodes that have that method on a successful parse" do
    input = @terminal.prefix
    index = 0
    parser = parser_with_empty_cache_mock
    
    result = @terminal.parse_at(input, index, parser)
    result.should be_success
    result.should respond_to(:method)
  end
end

describe "A terminal symbol matching 'end'" do
  before do
    @terminal = TerminalSymbol.new('end')
  end
  it "shold not match anything other than end" do
    input = "crack\nend"
    @terminal.parse_at(input, 0, parser_with_empty_cache_mock).should be_failure
  end
end

describe "A terminal symbol generated by TerminalSymbol.epsilon" do
  before do
    @terminal = TerminalSymbol.epsilon
  end
  
  it "should be epsilon" do
    @terminal.should be_epsilon
  end
end