dir = File.dirname(__FILE__)
require File.join(dir, *%w[compiler lexical_address_space])
require File.join(dir, *%w[compiler ruby_builder])
require File.join(dir, *%w[compiler parsing_expression_generator])
require File.join(dir, *%w[compiler compiler])
