dir = File.dirname(__FILE__)
require File.join(dir, *%w[compiler_2 lexical_address_space])
require File.join(dir, *%w[compiler_2 ruby_builder])
require File.join(dir, *%w[compiler_2 parsing_expression])
require File.join(dir, *%w[compiler_2 compiler])
require File.join(dir, *%w[compiler_2 metagrammar])
